apiVersion: v1
kind: Service
metadata:
  name: {{ include "spring-boot-helloworld.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "spring-boot-helloworld.name" . }}
    helm.sh/chart: {{ include "spring-boot-helloworld.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
      protocol: TCP

  selector:
    app.kubernetes.io/name: {{ include "spring-boot-helloworld.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}